### PR TITLE
handling background-images where url() has whitespaces

### LINKED ISSUE #159: handling `background-image`s where `url()` has whitespaces
**Description**
while importing https://www.sunstar-engineering.com/air we ran into an interesting issue - if one checks the source HTML of the URL and searches for `background-image: url(` they'd find a bunch of `div`s which are styled such.

when we try to import this URL and apply the suggestion at [0] to inline the `background-image` styles, it works on Safari and Firefox (Mac), but fails on Chrome (Mac) and Edge (Mac) (the `style['background-image']` at [1] comes up as an empty string).

**To Reproduce**
1. Fire up the importer via `hlx import`
2. patch the `tools/importer/import.js` as suggested [here](https://github.com/adobe/helix-importer-ui/blob/main/importer-guidelines.md#convert-background-images) or [here](https://github.com/adobe/helix-importer-ui/blob/main/importer-guidelines.md#styles)
3. import https://www.sunstar-engineering.com/air (at least until it moves over to Franklin stack 😅) or any other webpage that adds inline background image style as `background-image:url( /path/to/image.jpg )` (note the whitespace after and before the parens in the attribute-value

**Expected behavior**
Images should be inlined and appear in the generated doc/markdown/semantic-html

**Screenshots**
Works as expected on Safari and Firefox (Mac), fails to inline images on Chrome (Mac) and Edge (Mac)

**Version:**
```
hlx --version
14.23.6
```

**Additional context**
@sdmcraft pointed out that the reason could be leading and trailing space surrouding the `path` in `url()` - and he implemented a workaround at project level [2] which works. Obviously it is far better to have this addressed in importer since spec allows it [3]

my suspicion from initial debugging indicates two suspects
* how `Chromium` handles the `fetch` responses: adding a log-point at [4] and executing the importer in Chrome and Firefox produces HTML strings with different tokens for background-image URLs (Chrome has the exact same markup as the HTML has, whereas Firefox replaces surrounding whitespace with `"`)
* how `jsdom` handles surrounding spaces in `url()` args: since spec [2] allows whitespaces, `jsdom` shouldn't really care and should update the style correctly in the DOM it creates. it doesn't do that as can be noted by examining the `document` for elements with background-styles after applying a breakpoint at [5].

[0] https://github.com/adobe/helix-importer-ui/blob/main/importer-guidelines.md#convert-background-images
[1] https://github.com/adobe/helix-importer/blob/7c96ab0cc52d816ef3e4d17619312f2f199b2632/src/utils/DOMUtils.js#L259
[2] https://github.com/hlxsites/sunstar-engineering/blob/2ee64380b71d1e2ec97507f3df8e9142a4eedcb4/tools/importer/import.js#L146-L151
[3] https://drafts.csswg.org/css-syntax/#url-token-diagram (see `ws*` after and before opening and closing parens, respectively)
[4] https://github.com/adobe/helix-importer/blob/7c96ab0cc52d816ef3e4d17619312f2f199b2632/src/importer/PageImporter.js#L273
[5] https://github.com/adobe/helix-importer/blob/7c96ab0cc52d816ef3e4d17619312f2f199b2632/src/importer/PageImporter.js#L289

### PR DESCRIPTION
**Pull request by actinium15**
Fixes #159

### CODE REVIEW

File: src/utils/DOMUtils.js [hunk 1]
```diff
@@ -256,12 +256,24 @@ export default class DOMUtils {
...
+      styleAttr.forEach((style) => {
+        const [prop, value] = style.split(':');
+        if (prop === 'background-image') {
+          const trimmedValue = value.replace(/\s/g, '');
+          const elStyle = element.style;
+          elStyle.backgroundImage = trimmedValue;
+        }
+      });
+      const url = element.style.backgroundImage;
+      console.log(`inlining background-image for ${element.outerHTML}`);
```
Comment (kptdobe) [inline src/utils/DOMUtils.js:270]:
```suggestion
```

**Review by kptdobe — APPROVED** [review]
LGTM, thanks for providing the fix!

**Comment by actinium15** [comment]
@kptdobe, would you be kind enough to merge this? TIA!
